name: Unused

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/unused.yml'
  push:
    branches:
      - develop
    paths:
      - '**.php'
      - 'composer.*'
      - '.github/workflows/unused.yml'

jobs:
  rector:
    uses: codeigniter4/.github/.github/workflows/unused.yml@CI46
